#!/bin/bash
MY_PATH="`dirname \"$0\"`"
cd "$MY_PATH"
HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="Creado por: Elsoberanox - https://www.youtube.com/c/JuegosenLinux"
TITLE="www.juegosenlinux.site"
MENU="Castlevania Lords of Shadow Mirror of Fate - Elsoberanox"

OPTIONS=(1 "Instalar CMOF"
         2 "Desinstalar"
         3 "Ver mas ports"
         4 "Salir")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
#!/bin/bash
MY_PATH="`dirname \"$0\"`"
cd "$MY_PATH"
sudo cp winetricks /usr/bin/
sudo chmod +x badown
wget https://archive.org/download/wineson.7z_202110/wineson.7z
7z x wineson.7z 
sudo rm -R wineson.7z
sudo mv wineson /opt/
./badown https://www.mediafire.com/file/gx339baidkx5zda/CMOF.7z/file
7z x CMOF.7z
sudo rm -R CMOF.7z
mkdir $HOME/Juegos/
mkdir $HOME/Juegos/CMOF/
cd CMOF
export WINEPREFIX=$HOME/Juegos/CMOF/
export PATH=/opt/wineson/bin/:/usr/bin/
wine setup.exe
cp Crack/* $HOME/Juegos/CMOF/drive_c/Program\ Files\ \(x86\)/Castlevania\ Lords\ of\ Shadow\ Mirror\ of\ Fate\ HD/
cd ..
sudo rm -R cd CMOF
echo -e "cd $HOME/Juegos/CMOF/drive_c/Program\ Files\ \(x86\)/Castlevania\ Lords\ of\ Shadow\ Mirror\ of\ Fate\ HD/\nexport PATH=/opt/wineson/bin/\nwine CMOF.exe" >> cmof-bin
sudo chmod +x cmof-bin
sudo mv cmof-bin /usr/bin/


wget https://archive.org/download/castle_202110/castle.png
sudo mv castle.png /opt/
echo -e "[Desktop Entry]\n Version=1.0\n Type=Application\n Name=CMOF\n Comment=cmof-bin\n Icon=/opt/castle.png\n Exec=cmof-bin\n Categories=Game;" >> CMOF.desktop
sudo chmod +x CMOF.desktop
sudo mv CMOF.desktop $HOME/.local/share/applications
xdg-desktop-menu forceupdate


            ;;
        2)
sudo rm -R /usr/bin/winetricks
sudo rm -R /opt/wineson
sudo rm -R /usr/bin/cmof-bin
sudo rm -R /opt/castle.png
sudo rm -R $HOME/Juegos/CMOF/
sudo rm -R $HOME/.local/share/applications/CMOF.desktop
xdg-desktop-menu forceupdate

            ;;
        3)
            xdg-open https://www.juegosenlinux.site/
            ;;
            
                    3)
            exit
            ;;
esac
